import type { Device, NotchGeometry } from '../types';
import { makeDevice, UA, phoneButtons } from './helpers';

/** Classic sensor notch used by iPhone X → 14 (non-Pro). */
const notch: NotchGeometry = { type: 'notch', width: 160, height: 30, top: 0, radius: 20 };

/** Dynamic Island introduced with iPhone 14 Pro. */
const island: NotchGeometry = { type: 'island', width: 125, height: 35, top: 11, radius: 18 };

const iosSafe = { top: 47, right: 0, bottom: 34, left: 0 };
const iosSafeIsland = { top: 59, right: 0, bottom: 34, left: 0 };

/**
 * Apple iPhone catalog. A representative core spanning the classic home-button
 * era through the Dynamic Island generation.
 */
export const appleIphones: Device[] = [
  makeDevice({
    id: 'iphone-se-3',
    name: 'iPhone SE (3rd Gen)',
    manufacturer: 'Apple',
    category: 'phone',
    releaseYear: 2022,
    os: 'iOS 17',
    viewport: { width: 375, height: 667 },
    pixelRatio: 2,
    cornerRadius: 0,
    bezel: 22,
    statusBarHeight: 20,
    hardwareButtons: phoneButtons,
    userAgent: UA.iosPhone(),
  }),
  makeDevice({
    id: 'iphone-8',
    name: 'iPhone 8',
    manufacturer: 'Apple',
    category: 'phone',
    releaseYear: 2017,
    os: 'iOS 16',
    viewport: { width: 375, height: 667 },
    pixelRatio: 2,
    bezel: 22,
    statusBarHeight: 20,
    hardwareButtons: phoneButtons,
    userAgent: UA.iosPhone('16_7'),
  }),
  makeDevice({
    id: 'iphone-x',
    name: 'iPhone X',
    manufacturer: 'Apple',
    category: 'phone',
    releaseYear: 2017,
    os: 'iOS 16',
    viewport: { width: 375, height: 812 },
    pixelRatio: 3,
    cornerRadius: 40,
    notch,
    safeAreaInsets: iosSafe,
    statusBarHeight: 44,
    navBarHeight: 34,
    hardwareButtons: phoneButtons,
    userAgent: UA.iosPhone('16_7'),
  }),
  makeDevice({
    id: 'iphone-11',
    name: 'iPhone 11',
    manufacturer: 'Apple',
    category: 'phone',
    releaseYear: 2019,
    os: 'iOS 17',
    viewport: { width: 414, height: 896 },
    pixelRatio: 2,
    cornerRadius: 40,
    notch,
    safeAreaInsets: iosSafe,
    statusBarHeight: 44,
    navBarHeight: 34,
    hardwareButtons: phoneButtons,
    userAgent: UA.iosPhone(),
  }),
  makeDevice({
    id: 'iphone-12',
    name: 'iPhone 12',
    manufacturer: 'Apple',
    category: 'phone',
    releaseYear: 2020,
    os: 'iOS 17',
    viewport: { width: 390, height: 844 },
    pixelRatio: 3,
    cornerRadius: 47,
    notch,
    safeAreaInsets: iosSafe,
    statusBarHeight: 47,
    navBarHeight: 34,
    hardwareButtons: phoneButtons,
    userAgent: UA.iosPhone(),
  }),
  makeDevice({
    id: 'iphone-13',
    name: 'iPhone 13',
    manufacturer: 'Apple',
    category: 'phone',
    releaseYear: 2021,
    os: 'iOS 17',
    viewport: { width: 390, height: 844 },
    pixelRatio: 3,
    cornerRadius: 47,
    notch: { ...notch, width: 140 },
    safeAreaInsets: iosSafe,
    statusBarHeight: 47,
    navBarHeight: 34,
    hardwareButtons: phoneButtons,
    userAgent: UA.iosPhone(),
  }),
  makeDevice({
    id: 'iphone-13-mini',
    name: 'iPhone 13 Mini',
    manufacturer: 'Apple',
    category: 'phone',
    releaseYear: 2021,
    os: 'iOS 17',
    viewport: { width: 375, height: 812 },
    pixelRatio: 3,
    cornerRadius: 44,
    notch: { ...notch, width: 140 },
    safeAreaInsets: iosSafe,
    statusBarHeight: 50,
    navBarHeight: 34,
    hardwareButtons: phoneButtons,
    userAgent: UA.iosPhone(),
  }),
  makeDevice({
    id: 'iphone-14',
    name: 'iPhone 14',
    manufacturer: 'Apple',
    category: 'phone',
    releaseYear: 2022,
    os: 'iOS 17',
    viewport: { width: 390, height: 844 },
    pixelRatio: 3,
    cornerRadius: 47,
    notch: { ...notch, width: 140 },
    safeAreaInsets: iosSafe,
    statusBarHeight: 47,
    navBarHeight: 34,
    hardwareButtons: phoneButtons,
    userAgent: UA.iosPhone(),
  }),
  makeDevice({
    id: 'iphone-14-pro',
    name: 'iPhone 14 Pro',
    manufacturer: 'Apple',
    category: 'phone',
    releaseYear: 2022,
    os: 'iOS 17',
    viewport: { width: 393, height: 852 },
    pixelRatio: 3,
    cornerRadius: 55,
    notch: island,
    safeAreaInsets: iosSafeIsland,
    statusBarHeight: 59,
    navBarHeight: 34,
    hardwareButtons: phoneButtons,
    userAgent: UA.iosPhone(),
  }),
  makeDevice({
    id: 'iphone-15',
    name: 'iPhone 15',
    manufacturer: 'Apple',
    category: 'phone',
    releaseYear: 2023,
    os: 'iOS 17',
    viewport: { width: 393, height: 852 },
    pixelRatio: 3,
    cornerRadius: 55,
    notch: island,
    safeAreaInsets: iosSafeIsland,
    statusBarHeight: 59,
    navBarHeight: 34,
    hardwareButtons: phoneButtons,
    userAgent: UA.iosPhone(),
  }),
  makeDevice({
    id: 'iphone-15-pro',
    name: 'iPhone 15 Pro',
    manufacturer: 'Apple',
    category: 'phone',
    releaseYear: 2023,
    os: 'iOS 17',
    viewport: { width: 393, height: 852 },
    pixelRatio: 3,
    cornerRadius: 55,
    notch: island,
    safeAreaInsets: iosSafeIsland,
    statusBarHeight: 59,
    navBarHeight: 34,
    hardwareButtons: [
      { side: 'right', offset: 0.18, length: 0.09, label: 'Power' },
      { side: 'left', offset: 0.14, length: 0.05, label: 'Action Button' },
      { side: 'left', offset: 0.22, length: 0.07, label: 'Volume Up' },
      { side: 'left', offset: 0.31, length: 0.07, label: 'Volume Down' },
    ],
    userAgent: UA.iosPhone(),
  }),
  makeDevice({
    id: 'iphone-15-pro-max',
    name: 'iPhone 15 Pro Max',
    manufacturer: 'Apple',
    category: 'phone',
    releaseYear: 2023,
    os: 'iOS 17',
    viewport: { width: 430, height: 932 },
    pixelRatio: 3,
    cornerRadius: 55,
    notch: island,
    safeAreaInsets: iosSafeIsland,
    statusBarHeight: 59,
    navBarHeight: 34,
    hardwareButtons: phoneButtons,
    userAgent: UA.iosPhone(),
  }),
  makeDevice({
    id: 'iphone-16-pro',
    name: 'iPhone 16 Pro',
    manufacturer: 'Apple',
    category: 'phone',
    releaseYear: 2024,
    os: 'iOS 18',
    viewport: { width: 402, height: 874 },
    pixelRatio: 3,
    cornerRadius: 55,
    notch: island,
    safeAreaInsets: iosSafeIsland,
    statusBarHeight: 62,
    navBarHeight: 34,
    hardwareButtons: [
      { side: 'right', offset: 0.18, length: 0.09, label: 'Power' },
      { side: 'right', offset: 0.4, length: 0.05, label: 'Camera Control' },
      { side: 'left', offset: 0.14, length: 0.05, label: 'Action Button' },
      { side: 'left', offset: 0.22, length: 0.07, label: 'Volume Up' },
      { side: 'left', offset: 0.31, length: 0.07, label: 'Volume Down' },
    ],
    userAgent: UA.iosPhone('18_0'),
  }),
  makeDevice({
    id: 'iphone-16-pro-max',
    name: 'iPhone 16 Pro Max',
    manufacturer: 'Apple',
    category: 'phone',
    releaseYear: 2024,
    os: 'iOS 18',
    viewport: { width: 440, height: 956 },
    pixelRatio: 3,
    cornerRadius: 55,
    notch: island,
    safeAreaInsets: iosSafeIsland,
    statusBarHeight: 62,
    navBarHeight: 34,
    hardwareButtons: phoneButtons,
    userAgent: UA.iosPhone('18_0'),
  }),
];
