import type { Device } from '../types';
import { makeDevice, UA } from './helpers';

const ipadSafe = { top: 24, right: 0, bottom: 20, left: 0 };

/** Apple iPad catalog. */
export const appleIpads: Device[] = [
  makeDevice({
    id: 'ipad-mini',
    name: 'iPad Mini',
    manufacturer: 'Apple',
    category: 'tablet',
    releaseYear: 2021,
    os: 'iPadOS 17',
    viewport: { width: 744, height: 1133 },
    pixelRatio: 2,
    cornerRadius: 24,
    bezel: 28,
    safeAreaInsets: ipadSafe,
    statusBarHeight: 24,
    hardwareButtons: [
      { side: 'top', offset: 0.75, length: 0.08, label: 'Power' },
      { side: 'right', offset: 0.06, length: 0.12, label: 'Volume' },
    ],
    userAgent: UA.iosPad(),
  }),
  makeDevice({
    id: 'ipad-10',
    name: 'iPad (10th Gen)',
    manufacturer: 'Apple',
    category: 'tablet',
    releaseYear: 2022,
    os: 'iPadOS 17',
    viewport: { width: 820, height: 1180 },
    pixelRatio: 2,
    cornerRadius: 22,
    bezel: 30,
    safeAreaInsets: ipadSafe,
    statusBarHeight: 24,
    userAgent: UA.iosPad(),
  }),
  makeDevice({
    id: 'ipad-air-11',
    name: 'iPad Air 11"',
    manufacturer: 'Apple',
    category: 'tablet',
    releaseYear: 2024,
    os: 'iPadOS 17',
    viewport: { width: 820, height: 1180 },
    pixelRatio: 2,
    cornerRadius: 22,
    bezel: 26,
    safeAreaInsets: ipadSafe,
    statusBarHeight: 24,
    userAgent: UA.iosPad(),
  }),
  makeDevice({
    id: 'ipad-pro-11',
    name: 'iPad Pro 11"',
    manufacturer: 'Apple',
    category: 'tablet',
    releaseYear: 2024,
    os: 'iPadOS 17',
    viewport: { width: 834, height: 1194 },
    pixelRatio: 2,
    cornerRadius: 20,
    bezel: 22,
    safeAreaInsets: ipadSafe,
    statusBarHeight: 24,
    userAgent: UA.iosPad(),
  }),
  makeDevice({
    id: 'ipad-pro-13',
    name: 'iPad Pro 13"',
    manufacturer: 'Apple',
    category: 'tablet',
    releaseYear: 2024,
    os: 'iPadOS 17',
    viewport: { width: 1024, height: 1366 },
    pixelRatio: 2,
    cornerRadius: 20,
    bezel: 24,
    safeAreaInsets: ipadSafe,
    statusBarHeight: 24,
    userAgent: UA.iosPad(),
  }),
];
