import type { Device, NotchGeometry } from '../types';
import { makeDevice, UA, phoneButtons } from './helpers';

/** Centered punch-hole camera used by recent Pixel phones. */
const punchCenter: NotchGeometry = {
  type: 'punch-hole-center',
  width: 24,
  height: 24,
  top: 12,
  radius: 12,
};

const androidSafe = { top: 24, right: 0, bottom: 24, left: 0 };

/** Google Pixel catalog. */
export const googlePixels: Device[] = [
  makeDevice({
    id: 'pixel-5',
    name: 'Pixel 5',
    manufacturer: 'Google',
    category: 'phone',
    releaseYear: 2020,
    os: 'Android 14',
    viewport: { width: 393, height: 851 },
    pixelRatio: 2.75,
    cornerRadius: 36,
    notch: { type: 'punch-hole', width: 22, height: 22, top: 12, radius: 11 },
    safeAreaInsets: androidSafe,
    statusBarHeight: 24,
    navBarHeight: 24,
    hardwareButtons: phoneButtons,
    userAgent: UA.android('Pixel 5'),
  }),
  makeDevice({
    id: 'pixel-7',
    name: 'Pixel 7',
    manufacturer: 'Google',
    category: 'phone',
    releaseYear: 2022,
    os: 'Android 14',
    viewport: { width: 412, height: 915 },
    pixelRatio: 2.625,
    cornerRadius: 40,
    notch: punchCenter,
    safeAreaInsets: androidSafe,
    statusBarHeight: 28,
    navBarHeight: 24,
    hardwareButtons: phoneButtons,
    userAgent: UA.android('Pixel 7'),
  }),
  makeDevice({
    id: 'pixel-8',
    name: 'Pixel 8',
    manufacturer: 'Google',
    category: 'phone',
    releaseYear: 2023,
    os: 'Android 14',
    viewport: { width: 412, height: 915 },
    pixelRatio: 2.625,
    cornerRadius: 42,
    notch: punchCenter,
    safeAreaInsets: androidSafe,
    statusBarHeight: 28,
    navBarHeight: 24,
    hardwareButtons: phoneButtons,
    userAgent: UA.android('Pixel 8'),
  }),
  makeDevice({
    id: 'pixel-8-pro',
    name: 'Pixel 8 Pro',
    manufacturer: 'Google',
    category: 'phone',
    releaseYear: 2023,
    os: 'Android 14',
    viewport: { width: 448, height: 992 },
    pixelRatio: 2.625,
    cornerRadius: 44,
    notch: punchCenter,
    safeAreaInsets: androidSafe,
    statusBarHeight: 28,
    navBarHeight: 24,
    hardwareButtons: phoneButtons,
    userAgent: UA.android('Pixel 8 Pro'),
  }),
  makeDevice({
    id: 'pixel-9-pro',
    name: 'Pixel 9 Pro',
    manufacturer: 'Google',
    category: 'phone',
    releaseYear: 2024,
    os: 'Android 15',
    viewport: { width: 402, height: 874 },
    pixelRatio: 3,
    cornerRadius: 44,
    notch: punchCenter,
    safeAreaInsets: androidSafe,
    statusBarHeight: 28,
    navBarHeight: 24,
    hardwareButtons: phoneButtons,
    userAgent: UA.android('Pixel 9 Pro', '15'),
  }),
  makeDevice({
    id: 'pixel-tablet',
    name: 'Pixel Tablet',
    manufacturer: 'Google',
    category: 'tablet',
    releaseYear: 2023,
    os: 'Android 14',
    viewport: { width: 1600, height: 2560 },
    pixelRatio: 1,
    cornerRadius: 24,
    bezel: 30,
    safeAreaInsets: { top: 24, right: 0, bottom: 24, left: 0 },
    statusBarHeight: 24,
    navBarHeight: 24,
    userAgent: UA.androidTablet('Pixel Tablet'),
  }),
];
