import type { Device, NotchGeometry } from '../types';
import { makeDevice, UA, phoneButtons } from './helpers';

const punchCenter: NotchGeometry = {
  type: 'punch-hole-center',
  width: 22,
  height: 22,
  top: 10,
  radius: 11,
};

const androidSafe = { top: 24, right: 0, bottom: 20, left: 0 };

/** OnePlus, Xiaomi, Nothing, Motorola, Sony, and other Android makers. */
export const otherAndroidDevices: Device[] = [
  makeDevice({
    id: 'oneplus-12',
    name: 'OnePlus 12',
    manufacturer: 'OnePlus',
    category: 'phone',
    releaseYear: 2024,
    os: 'Android 14',
    viewport: { width: 412, height: 919 },
    pixelRatio: 3.5,
    cornerRadius: 40,
    notch: punchCenter,
    safeAreaInsets: androidSafe,
    statusBarHeight: 26,
    navBarHeight: 20,
    hardwareButtons: phoneButtons,
    userAgent: UA.android('PJD110'),
  }),
  makeDevice({
    id: 'xiaomi-14',
    name: 'Xiaomi 14',
    manufacturer: 'Xiaomi',
    category: 'phone',
    releaseYear: 2024,
    os: 'Android 14',
    viewport: { width: 393, height: 873 },
    pixelRatio: 3,
    cornerRadius: 38,
    notch: punchCenter,
    safeAreaInsets: androidSafe,
    statusBarHeight: 26,
    navBarHeight: 20,
    hardwareButtons: phoneButtons,
    userAgent: UA.android('23127PN0CG'),
  }),
  makeDevice({
    id: 'redmi-note-13',
    name: 'Redmi Note 13',
    manufacturer: 'Xiaomi',
    category: 'phone',
    releaseYear: 2024,
    os: 'Android 13',
    viewport: { width: 393, height: 873 },
    pixelRatio: 2.75,
    cornerRadius: 34,
    notch: punchCenter,
    safeAreaInsets: androidSafe,
    statusBarHeight: 26,
    navBarHeight: 20,
    hardwareButtons: phoneButtons,
    userAgent: UA.android('23124RA7EO', '13'),
  }),
  makeDevice({
    id: 'nothing-phone-2',
    name: 'Nothing Phone (2)',
    manufacturer: 'Nothing',
    category: 'phone',
    releaseYear: 2023,
    os: 'Android 14',
    viewport: { width: 412, height: 915 },
    pixelRatio: 2.6,
    cornerRadius: 40,
    notch: punchCenter,
    safeAreaInsets: androidSafe,
    statusBarHeight: 26,
    navBarHeight: 20,
    hardwareButtons: phoneButtons,
    userAgent: UA.android('A065'),
  }),
  makeDevice({
    id: 'motorola-edge-50',
    name: 'Motorola Edge 50',
    manufacturer: 'Motorola',
    category: 'phone',
    releaseYear: 2024,
    os: 'Android 14',
    viewport: { width: 393, height: 873 },
    pixelRatio: 2.75,
    cornerRadius: 38,
    notch: punchCenter,
    safeAreaInsets: androidSafe,
    statusBarHeight: 26,
    navBarHeight: 20,
    hardwareButtons: phoneButtons,
    userAgent: UA.android('XT2401-1'),
  }),
  makeDevice({
    id: 'sony-xperia-1-vi',
    name: 'Sony Xperia 1 VI',
    manufacturer: 'Sony',
    category: 'phone',
    releaseYear: 2024,
    os: 'Android 14',
    viewport: { width: 412, height: 915 },
    pixelRatio: 3.5,
    cornerRadius: 20,
    notch: { type: 'none', width: 0, height: 0, top: 0, radius: 0 },
    safeAreaInsets: { top: 30, right: 0, bottom: 20, left: 0 },
    statusBarHeight: 30,
    navBarHeight: 20,
    hardwareButtons: phoneButtons,
    userAgent: UA.android('XQ-EC72'),
  }),
];
