import type { Device, NotchGeometry } from '../types';
import { makeDevice, UA, phoneButtons } from './helpers';

const punchCenter: NotchGeometry = {
  type: 'punch-hole-center',
  width: 22,
  height: 22,
  top: 10,
  radius: 11,
};

const androidSafe = { top: 24, right: 0, bottom: 20, left: 0 };

/** Samsung Galaxy phones and tablets (non-foldable). */
export const samsungDevices: Device[] = [
  makeDevice({
    id: 'galaxy-s21',
    name: 'Galaxy S21',
    manufacturer: 'Samsung',
    category: 'phone',
    releaseYear: 2021,
    os: 'Android 14',
    viewport: { width: 360, height: 800 },
    pixelRatio: 3,
    cornerRadius: 32,
    notch: punchCenter,
    safeAreaInsets: androidSafe,
    statusBarHeight: 24,
    navBarHeight: 20,
    hardwareButtons: phoneButtons,
    userAgent: UA.android('SM-G991B'),
  }),
  makeDevice({
    id: 'galaxy-s23',
    name: 'Galaxy S23',
    manufacturer: 'Samsung',
    category: 'phone',
    releaseYear: 2023,
    os: 'Android 14',
    viewport: { width: 360, height: 780 },
    pixelRatio: 3,
    cornerRadius: 34,
    notch: punchCenter,
    safeAreaInsets: androidSafe,
    statusBarHeight: 24,
    navBarHeight: 20,
    hardwareButtons: phoneButtons,
    userAgent: UA.android('SM-S911B'),
  }),
  makeDevice({
    id: 'galaxy-s24',
    name: 'Galaxy S24',
    manufacturer: 'Samsung',
    category: 'phone',
    releaseYear: 2024,
    os: 'Android 14',
    viewport: { width: 360, height: 780 },
    pixelRatio: 3,
    cornerRadius: 34,
    notch: punchCenter,
    safeAreaInsets: androidSafe,
    statusBarHeight: 24,
    navBarHeight: 20,
    hardwareButtons: phoneButtons,
    userAgent: UA.android('SM-S921B'),
  }),
  makeDevice({
    id: 'galaxy-s24-ultra',
    name: 'Galaxy S24 Ultra',
    manufacturer: 'Samsung',
    category: 'phone',
    releaseYear: 2024,
    os: 'Android 14',
    viewport: { width: 384, height: 824 },
    pixelRatio: 3.75,
    cornerRadius: 24,
    notch: punchCenter,
    safeAreaInsets: androidSafe,
    statusBarHeight: 24,
    navBarHeight: 20,
    hardwareButtons: phoneButtons,
    userAgent: UA.android('SM-S928B'),
  }),
  makeDevice({
    id: 'galaxy-s25-ultra',
    name: 'Galaxy S25 Ultra',
    manufacturer: 'Samsung',
    category: 'phone',
    releaseYear: 2025,
    os: 'Android 15',
    viewport: { width: 384, height: 832 },
    pixelRatio: 3.75,
    cornerRadius: 26,
    notch: punchCenter,
    safeAreaInsets: androidSafe,
    statusBarHeight: 24,
    navBarHeight: 20,
    hardwareButtons: phoneButtons,
    userAgent: UA.android('SM-S938B', '15'),
  }),
  makeDevice({
    id: 'galaxy-tab-s9',
    name: 'Galaxy Tab S9',
    manufacturer: 'Samsung',
    category: 'tablet',
    releaseYear: 2023,
    os: 'Android 14',
    viewport: { width: 800, height: 1280 },
    pixelRatio: 2,
    cornerRadius: 18,
    bezel: 26,
    safeAreaInsets: { top: 24, right: 0, bottom: 20, left: 0 },
    statusBarHeight: 24,
    navBarHeight: 20,
    userAgent: UA.androidTablet('SM-X710'),
  }),
];
