import type { Device } from '../types';
import { makeDevice, UA } from './helpers';

/** Smartwatch presets (rounded / squircle displays). */
export const watchDevices: Device[] = [
  makeDevice({
    id: 'apple-watch-ultra',
    name: 'Apple Watch Ultra',
    manufacturer: 'Apple',
    category: 'watch',
    releaseYear: 2023,
    os: 'watchOS 10',
    viewport: { width: 205, height: 251 },
    pixelRatio: 2,
    cornerRadius: 44,
    bezel: 20,
    orientations: ['portrait'],
    safeAreaInsets: { top: 12, right: 8, bottom: 12, left: 8 },
    hardwareButtons: [
      { side: 'right', offset: 0.3, length: 0.14, label: 'Digital Crown' },
      { side: 'right', offset: 0.5, length: 0.1, label: 'Side Button' },
      { side: 'left', offset: 0.4, length: 0.12, label: 'Action Button' },
    ],
    userAgent: UA.watch,
  }),
  makeDevice({
    id: 'apple-watch-s10',
    name: 'Apple Watch Series 10',
    manufacturer: 'Apple',
    category: 'watch',
    releaseYear: 2024,
    os: 'watchOS 11',
    viewport: { width: 208, height: 248 },
    pixelRatio: 2,
    cornerRadius: 56,
    bezel: 16,
    orientations: ['portrait'],
    safeAreaInsets: { top: 12, right: 8, bottom: 12, left: 8 },
    hardwareButtons: [
      { side: 'right', offset: 0.34, length: 0.14, label: 'Digital Crown' },
      { side: 'right', offset: 0.54, length: 0.1, label: 'Side Button' },
    ],
    userAgent: UA.watch,
  }),
  makeDevice({
    id: 'pixel-watch-3',
    name: 'Pixel Watch 3',
    manufacturer: 'Google',
    category: 'watch',
    releaseYear: 2024,
    os: 'Wear OS 5',
    viewport: { width: 192, height: 192 },
    pixelRatio: 2,
    cornerRadius: 96,
    bezel: 18,
    orientations: ['portrait'],
    safeAreaInsets: { top: 10, right: 10, bottom: 10, left: 10 },
    hardwareButtons: [{ side: 'right', offset: 0.4, length: 0.14, label: 'Crown' }],
    userAgent: UA.watch,
  }),
  makeDevice({
    id: 'galaxy-watch-ultra',
    name: 'Galaxy Watch Ultra',
    manufacturer: 'Samsung',
    category: 'watch',
    releaseYear: 2024,
    os: 'Wear OS 5',
    viewport: { width: 214, height: 214 },
    pixelRatio: 2,
    cornerRadius: 90,
    bezel: 22,
    orientations: ['portrait'],
    safeAreaInsets: { top: 12, right: 12, bottom: 12, left: 12 },
    hardwareButtons: [
      { side: 'right', offset: 0.34, length: 0.12, label: 'Home' },
      { side: 'right', offset: 0.5, length: 0.12, label: 'Back' },
    ],
    userAgent: UA.watch,
  }),
];
